### ISSUE TITLE
Feedback Data-Dashboard

### ISSUE THREAD

**Issue by mikenieva** [AMHymyilee/cdmx-2018-06-bc-core-am-data-dashboard#1]
Adri, qué tal.

Te doy apreciaciones de tu Data-Dashboard:

**- General.** El proyecto está muy elegante y el diseño me gustó bastante. Lo único importante es ver que tienes una carpeta JS con código externo. Me importa mucho que puedas entender qué estás instalando/integrando a tu proyecto y puedas explicarlo.

**- JS.** Bien la abstracción. Me gusta bastante que ya estés utilizando funciones por separado. Me parece muy buena práctica

**- Tests.** Bien por el intento de los tests. Hay que practicar más con las funciones puras.

Amalia ya tuvo una entrevista técnica contigo y me comentó que te fue muy bien. Mi apreciación es muy breve pero en general positiva. Acércate si necesitas apoyo en un tema particular.

Bien Adri.

**Comment by AdrianaMoraGr** [comment]
Muchas gracias tomare en cuenta sus consejos
